apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        uid: tempo
        access: proxy
        url: http://tempo:3200
        isDefault: true
        editable: false
        jsonData:
          httpMethod: GET
      - name: Mimir
        type: prometheus
        uid: mimir
        access: proxy
        url: http://mimir:8080/prometheus
        isDefault: false
        editable: false
        jsonData:
          httpMethod: GET
          prometheusType: Mimir
