FROM rust:1-bookworm

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends cmake pkg-config libssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch --locked

CMD ["cargo", "watch", "-q", "-c", "-w", "src", "-w", "Cargo.toml", "-x", "run"]
