#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ECR_KUSTOMIZE="${ROOT}/k8s/overlays/prod/ecr/kustomization.yaml"
TAG="${IMAGE_TAG:-latest}"

SERVICES=(
  users
  chat
  public-api
  message-delivery
  message-storage
  frontend
)

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Write k8s/overlays/prod/ecr/kustomization.yaml so prod manifests pull from ECR
instead of docker.io.

Options:
  -h, --help    Show this help

Environment:
  ECR_REGISTRY   Full registry host (no trailing slash). Default: derived from AWS CLI.
  IMAGE_TAG      Image tag for all services (default: latest)
  AWS_REGION     Used when deriving ECR_REGISTRY
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

REGISTRY="${ECR_REGISTRY:-}"
if [[ -z "${REGISTRY}" ]]; then
  if ! command -v aws >/dev/null 2>&1; then
    echo "error: set ECR_REGISTRY or install AWS CLI" >&2
    exit 1
  fi
  AWS_REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-}}"
  if [[ -z "${AWS_REGION}" ]]; then
    AWS_REGION="$(aws configure get region 2>/dev/null || true)"
  fi
  if [[ -z "${AWS_REGION}" ]]; then
    echo "error: set AWS_REGION or configure a default region" >&2
    exit 1
  fi
  ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
  REGISTRY="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
fi

{
  echo "# Generated by scripts/configure-prod-ecr.sh — safe to re-run."
  echo "apiVersion: kustomize.config.k8s.io/v1alpha1"
  echo "kind: Component"
  echo
  echo "images:"
  for svc in "${SERVICES[@]}"; do
    echo "  - name: ${svc}"
    echo "    newName: ${REGISTRY}/${svc}"
    echo "    newTag: ${TAG}"
  done
} > "${ECR_KUSTOMIZE}"

echo "Configured prod overlay ECR registry: ${REGISTRY}"
echo "Image tag: ${TAG}"
echo "Updated: ${ECR_KUSTOMIZE}"
