apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - observability
  - chat-service.yaml
  - frontend-service.yaml
  - ingress.yaml
  - kafka-ui.yaml
  - kafka.yaml
  - message-delivery-service.yaml
  - message-storage-service-mongo.yaml
  - message-storage-service.yaml
  - mongo-express.yaml
  - public-api-service.yaml
  - users-service.yaml
